Repository norskeld/sigma, pull requests merged in 2023-01, with the labels that each got.

#56 fix(combinators/many): fix an edge case when combined with `noneOf`
  src/__tests__/combinators/many.spec.ts
  src/combinators/many.ts
Labels: bug

#59 fix(types): fix toUnion signature to correctly infer type
  src/types.ts
Labels: bug

#61 feat(parsers/regexp): add injection of global flag if it's not present
  docs/content/parsers/regexp.md
  src/__tests__/parsers/regexp.spec.ts
  src/parsers/regexp.ts
Labels: feat

#62 feat(parsers/tryRun): add `tryRun` parser
  docs/content/.vitepress/config.ts
  docs/content/parsers/run.md
  docs/content/parsers/tryRun.md
  docs/package-lock.json
  docs/package.json
  src/__tests__/@helpers/index.ts
  src/__tests__/parsers/tryRun.spec.ts
  src/parsers.ts
  src/parsers/tryRun.ts
Labels: feat

#63 docs: minor improvements
  docs/content/.vitepress/config.ts
  docs/content/.vitepress/helpers.ts
  docs/content/index.md
Labels: docs

#64 chore(naming): fix typos, add consistent naming, improve eslintignore
  .eslintignore
  src/__tests__/@helpers/index.ts
  src/__tests__/parsers/defer.spec.ts
  src/__tests__/parsers/eol.spec.ts
  src/__tests__/parsers/letter.spec.ts
  src/__tests__/parsers/numbers.spec.ts
  src/__tests__/parsers/run.spec.ts
  src/__tests__/parsers/string.spec.ts
  src/__tests__/utils/unicode.spec.ts
Labels: refactor

#67 docs(combinators/when): improve description, provide better example
  docs/content/combinators/when.md
Labels: docs

#72 chore(docs/config): add automatic sidebar generation, improve config
  docs/content/.vitepress/config.ts
  docs/content/.vitepress/helpers.ts
  docs/package-lock.json
  docs/package.json
Labels: A-types, A-docs, P-low, A-structure

#74 refactor(types): remove spans cast, fix JSDoc
  src/parsers/numbers.ts
  src/parsers/oneOf.ts
  src/parsers/tryRun.ts
Labels: A-types, P-low
